// <auto-generated />
using System;
using CrudOperations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudOperations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220509105614_data")]
    partial class data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CrudOperations.Models.Filiere", b =>
                {
                    b.Property<int>("FiliereId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FiliereId"), 1L, 1);

                    b.Property<string>("FiliereName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("FiliereId");

                    b.ToTable("Filieres");
                });

            modelBuilder.Entity("CrudOperations.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<int>("FiliereID")
                        .HasColumnType("int");

                    b.Property<string>("StudentImage")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("mobilePhone")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("StudentId");

                    b.HasIndex("FiliereID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CrudOperations.Models.Student", b =>
                {
                    b.HasOne("CrudOperations.Models.Filiere", "filiere")
                        .WithMany()
                        .HasForeignKey("FiliereID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("filiere");
                });
#pragma warning restore 612, 618
        }
    }
}
